repos:
  - repo: https://github.com/golangci/golangci-lint
    rev: v2.12.2
    hooks:
      - id: golangci-lint
        args: [--config, app/.golangci.yaml, ./app/...]
      - id: golangci-lint-fmt
        args: [--config, app/.golangci-fmt.yaml, ./app/...]

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.30.1
    hooks:
      - id: gitleaks
